# Exploratory Analysis of the MLS

In [43]:
import requests
import json
import pandas as pd

In [78]:
amer_soccer_mls_url = "https://app.americansocceranalysis.com/api/v1/mls/"
url = amer_soccer_mls_url + 'teams'
r = requests.get(url)

In [79]:
teams = pd.read_json(json.dumps(r.json()))
teams.head()

      team_id               team_name team_short_name team_abbreviation
0  0KPqjA456v    San Jose Earthquakes        San Jose               SJE
1  19vQ2095K6  New England Revolution     New England               NER
2  4wM42l4qjB              Chivas USA          Chivas               CHV
3  9z5k7Yg5A3      Philadelphia Union    Philadelphia               PHI
4  a2lqR4JMr0          Real Salt Lake       Salt Lake               RSL

In [81]:
url = amer_soccer_mls_url + 'games'
params = {'team_id':'WBLMvYAQxe'}
r = requests.get(url,params)

In [95]:
len(r.json())

324

In [94]:
pd.read_json(json.dumps(r.json()), convert_dates=False)

,game_id,date_time_utc,home_score,away_score,home_team_id,away_team_id,referee_id,stadium_id,home_manager_id,away_manager_id,expanded_minutes,season_name,matchday,attendance,knockout_game,last_updated_utc,extra_time,penalties,home_penalties,away_penalties
0,xW5pVWmJQg,2022-02-27 00:30:00 UTC,2,2,WBLMvYAQxe,19vQ2095K6,jYQJnoVQGR,p6qbX06M0G,gpMOYv1qzy,LeVq3j5WOJ,102,2022,1,23411,False,2022-03-02 09:48:22 UTC,NaN,NaN,NaN,NaN
1,aDQ037dpqE,2021-12-11 20:00:00 UTC,1,1,WBLMvYAQxe,Vj58weDM8n,gjMNk4v5Kp,p6qbX06M0G,gpMOYv1qzy,2lqRa4D5r0,131,2021,38,25218,True,2021-12-11 23:27:57 UTC,1.0,1.0,2.0,4.0
2,9vQ2W7a1MK,2021-12-04 23:30:00 UTC,2,0,WBLMvYAQxe,a2lqR4JMr0,0Oq6037M6D,p6qbX06M0G,gpMOYv1qzy,4wM4vOAqjB,97,2021,38,0,True,2021-12-07 09:57:31 UTC,NaN,NaN,NaN,NaN
3,Vj58o8E3M8,2021-11-25 21:30:00 UTC,0,1,pzeQZ6xQKw,WBLMvYAQxe,EGMPLlxMaY,9z5ka6gQA3,0Oq6VPgq6D,gpMOYv1qzy,100,2021,37,17438,True,2021-11-27 10:12:41 UTC,NaN,NaN,NaN,NaN
4,2vQ1B7a4Mr,2021-11-21 22:30:00 UTC,3,1,WBLMvYAQxe,kRQand1MKZ,gjMNk4v5Kp,p6qbX06M0G,gpMOYv1qzy,OlMlYvy5Lz,105,2021,36,22533,True,2021-11-24 07:26:56 UTC,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,raMyrN2l5d,2013-04-07 02:30:00 UTC,2,0,WBLMvYAQxe,YgOMngl5wN,odMXjR0qYL,p6qbX06M0G,NPqxkDY59d,4JMA4X9QKg,98,2013,6,20674,False,NaN,NaN,NaN,NaN,NaN
320,gOMnlGL8qw,2013-03-30 22:00:00 UTC,2,2,pzeQZ6xQKw,WBLMvYAQxe,Pk5LRpDQOW,9z5ka6gQA3,gjMNk8v5Kp,NPqxkDY59d,96,2013,5,11774,False,NaN,NaN,NaN,NaN,NaN
321,0Oq63oZxQ6,2013-03-17 00:00:00 UTC,1,1,jYQJ19EqGR,WBLMvYAQxe,315VrXb59x,9Yqda07QvJ,KXMeab1M64,NPqxkDY59d,99,2013,3,40150,False,NaN,NaN,NaN,NaN,NaN
322,e7MzJyeGMr,2013-03-10 03:30:00 UTC,1,2,WBLMvYAQxe,APk5LGOMOW,jYQJnnZQGR,p6qbX06M0G,NPqxkDY59d,315VKkEq9x,97,2013,2,20674,False,NaN,NaN,NaN,NaN,NaN
323,4JMAo1X1qK,2013-03-04 00:30:00 UTC,3,3,WBLMvYAQxe,a2lqRX2Mr0,9z5kJ7gMA3,p6qbX06M0G,NPqxkDY59d,aDQ009EQEv,98,2013,1,20674,False,NaN,NaN,NaN,NaN,NaN